// SPDX-FileCopyrightText: 2025 Antoni Szymański
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"fmt"
	"go/format"
	"os"
	"strconv"

	"github.com/alecthomas/kong"
	"github.com/antoniszymanski/mapcomments-go"
)

type Cli struct {
	Packages        []string `arg:""`
	Package         string   `short:"P" default:"main"`
	Output          string   `short:"O" type:"path" default:"commentmap_gen.go"`
	WithFullComment bool
}

func main() {
	var cli Cli
	ctx := kong.Parse(&cli,
		kong.Name("mapcomments"),
		kong.Description("A tool that extracts comments from Go files and generates a Go file with them as a map"),
		kong.UsageOnError(),
	)
	ctx.FatalIfErrorf(ctx.Run())
}

func (cli *Cli) Run() error {
	commentMap := make(map[string]string)
	for _, path := range cli.Packages {
		err := mapcomments.AddGoComments(commentMap, path, cli.WithFullComment)
		if err != nil {
			return fmt.Errorf("failed to add Go comments: %w", err)
		}
	}

	var b []byte
	b = append(b, "// Code generated by mapcomments; DO NOT EDIT.\n\npackage "...)
	b = append(b, cli.Package...)
	b = append(b, "\n\nfunc CommentMap() map[string]string {\nreturn map[string]string{\n"...)
	for key, value := range commentMap {
		if value != "" {
			b = strconv.AppendQuote(b, key)
			b = append(b, ": "...)
			b = strconv.AppendQuote(b, value)
			b = append(b, ",\n"...)
		}
	}
	b = append(b, "}}"...)

	data, err := format.Source(b)
	if err != nil {
		return fmt.Errorf("failed to format the generated code: %w", err)
	}

	if cli.Output == "-" {
		_, err = os.Stdout.Write(data)
	} else {
		err = os.WriteFile(cli.Output, data, 0600)
	}
	if err != nil {
		return fmt.Errorf("failed to write to the file: %w", err)
	}
	return nil
}
